---
title: "Vijay's dashboard"
subtitle: "Homer"
logo: "logo.png"

header: true
footer: false 

# theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  #  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #  title: "Demo !"
  #  icon: "fa fa-grin"
  #  content: "This is  homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Bio"
    icon: "fas fa-address-card"
    url: "https://l.vijayakumar.xyz"
  - name: "Blog"
    icon: "fas fa-book"
    url: "https://vijayakumar.xyz"
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/vijayakumarravi"
    target: "_blank" 
  - name: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/vijay.ig"
    target: "_blank" 
  - name: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/_vijayakumar_"
    target: "_blank" 
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

services:
  - name: "Dashboards"
    icon: "fas fa-cloud"
    items:
      - name: "cloudflare dash"
        logo: "https://dash.cloudflare.com/favicon.ico"
        subtitle: "Cloudflare admin dashboard"
        url: "https://dash.cloudflare.com/4fc118cc61e84408cd4335a7544714bd/vijayakumar.xyz"
        target: "_blank" 

      - name: "Cloudflare zero trust"
        logo: "https://dash.cloudflare.com/favicon.ico"
        subtitle: "Cloudflare zero trust"
        url: "https://one.dash.cloudflare.com/4fc118cc61e84408cd4335a7544714bd/"
        target: "_blank"

      - name: "Fly.io dash"
        logo: "https://fly.io/phx/ui/images/favicon/favicon-595d1312b35dfe32838befdf8505515e.ico?vsn=d"
        subtitle: "Fly.io Dashboard"
        url: "https://fly.io/dashboard/vijayakumar-ravi"
        target: "_blank"

      - name: "Render Dashboard"
        logo: "https://dashboard.render.com/favicon-dark.png"
        subtitle: "render.com vault dashboard"
        url: "https://dashboard.render.com/web/srv-cj9qb3hduelc73d91itg"
        target: "_blank"

      - name: "NextDNS Dashboard"
        logo: "https://my.nextdns.io/favicon.ico"
        subtitle: "NextDns setup dashboard"
        url: "https://my.nextdns.io/a28d42/setup"
        target: "_blank"

      - name: "Vercel Dashboard"
        logo: "https://vercel.com/favicon.ico"
        subtitle: "Vercel deployments dashboard"
        url: "https://vercel.com/dashboard"
        target: "_blank"

  - name: "Services"
    icon: "fas fa-server"
    items:
      - name: "Bitwarden"
        logo: "https://vault.bitwarden.com/favicon.ico"
        subtitle: "Password manager"
        url: "https://vault.vijayakumar.xyz"
        target: "_blank" 

      - name: "Uptime kuma"
        logo: "https://flytime.fly.dev/favicon.ico"
        subtitle: "self-hosted monitoring tool"
        url: "https://flytime.fly.dev"
        slug: "all"
        type: "UptimeKuma"
        target: "_blank"

      - name: "Immich"
        logo: "https://immich.app/img/favicon.png"
        subtitle: "Google photos alternative"
        url: "https://photo.vijayakumar.xyz"
        target: "_blank"

      - name: "Jellyfin"
        logo: "https://jellyfin.org/images/favicon.ico"
        subtitle: "Self-hosted media streaming system"
        url: "https://jellyfin.vijayakumar.xyz/"
        type: "Emby"
        apikey: "c3fa263cffb34a0fbef0dcf8e575961d"
        libraryType: "series" #Choose which stats to show. Can be one of: music, series or movies.
        target: "_blank"

      - name: "Umami"
        logo: "https://umami-vijay.vercel.app/favicon.ico"
        subtitle: "Umami is a privacy-focused alternative to Google Analytics."
        url: "https://umami-vijay.vercel.app/dashboard"
        target: "_blank"

      - name: "Onelink"
        logo: "https://dub.co/favicon-32x32.png"
        subtitle: "Link in bio tool"
        url: "https://onelink-vijay.vercel.app"
        target: "_blank"

  - name: "Local"
    icon: "fas fa-server"
    items:      
      - name: "Dockge"
        logo: "https://dockge.kuma.pet/icon.svg"
        subtitle: "easy-to-use docker compose stack manager"
        url: "http://10.0.0.3:5001/"
        target: "_blank"
      
      - name: "Jellyseerr"
        logo: "https://github.com/Fallenbagel/jellyseerr/blob/develop/public/android-chrome-512x512.png?raw=true"
        subtitle: "Media requesting system"
        url: "http://10.0.0.3:5055/"
        target: "_blank"
      
      - name: "Pihole"
        logo: "https://docs.pi-hole.net/images/favicon.ico"
        subtitle: "Dns ad blocker"
        url: "http://10.0.0.2/admin"
        type: "PiHole"
        target: "_blank"

      - name: "Duplicati"
        logo: "https://www.duplicati.com/images/duplicati-fb-share-v1.png"
        subtitle: "Remote backup solution"
        url: "http://10.0.0.3:8200/"
        target: "_blank"

      - name: "QBittorrent"
        logo: "https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/qbittorrent.ico"
        subtitle: "Torrent downloader"
        url: "http://10.0.0.3:8080/"
        target: "_blank"
      
  - name: "Mediarr"
    icon: "fas fa-compact-disc"
    items:      
      - name: "Prowlarr"
        logo: "https://prowlarr.com/img/favicon.ico"
        subtitle: "Index management"
        url: "http://10.0.0.3:9696/"
        target: "_blank"

      - name: "Lidarr"
        logo: "https://lidarr.audio/img/favicon.ico"
        subtitle: "Music management"
        url: "http://10.0.0.3:8686/"
        target: "_blank"

  - name: "Video"
    icon: "fas fa-video"
    items:      
      - name: "Sonarr"
        logo: "https://sonarr.tv/img/favicon.ico"
        subtitle: "Series management"
        url: "http://10.0.0.3:8989/"
        target: "_blank"

      - name: "Radarr"
        logo: "https://radarr.video/img/favicon.ico"
        subtitle: "Movie management"
        url: "http://10.0.0.3:7878/"
        target: "_blank"
