---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Vijay's dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  #  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #  title: "Demo !"
  #  icon: "fa fa-grin"
  #  content: "This is  homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Bio"
    icon: "fas fa-address-card"
    url: "https://l.vijayakumar.xyz"
  - name: "Blog"
    icon: "fas fa-book"
    url: "https://vijayakumar.xyz"
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/vijayakumarravi"
    target: "_blank" # optional html a tag target attribute
  - name: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/vijay.ig"
    target: "_blank" # optional html a tag target attribute
  - name: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/_vijayakumar_"
    target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Dashboards"
    icon: "fas fa-cloud"
    items:
      - name: "cloudflare dash"
        logo: "https://dash.cloudflare.com/favicon.ico"
        subtitle: "Cloudflare admin dashboard"
        tag: "dash"
        keywords: "Cloudflare admin dashboard"
        url: "https://dash.cloudflare.com/4fc118cc61e84408cd4335a7544714bd/vijayakumar.xyz"
        target: "_blank" # optional html a tag target attribute

      - name: "Cloudflare zero trust"
        logo: "https://dash.cloudflare.com/favicon.ico"
        subtitle: "Cloudflare zero trust"
        tag: "dash"
        url: "https://one.dash.cloudflare.com/4fc118cc61e84408cd4335a7544714bd/"
        target: "_blank"

      - name: "Fly.io dash"
        logo: "https://fly.io/phx/ui/images/favicon/favicon-595d1312b35dfe32838befdf8505515e.ico?vsn=d"
        subtitle: "Fly.io Dashboard"
        tag: "dash"
        url: "https://fly.io/dashboard/vijayakumar-ravi"
        target: "_blank"

      - name: "Render Dashboard"
        logo: "https://dashboard.render.com/favicon-dark.png"
        subtitle: "render.com vault dashboard"
        tag: "dash"
        url: "https://dashboard.render.com/web/srv-cj9qb3hduelc73d91itg"
        target: "_blank"

      - name: "NextDNS Dashboard"
        logo: "https://my.nextdns.io/favicon.ico"
        subtitle: "NextDns setup dashboard"
        tag: "dash"
        url: "https://my.nextdns.io/a28d42/setup"
        target: "_blank"

      - name: "Vercel Dashboard"
        logo: "https://vercel.com/favicon.ico"
        subtitle: "Vercel deployments dashboard"
        tag: "dash"
        url: "https://vercel.com/dashboard"
        target: "_blank"

  - name: "Services"
    icon: "fas fa-server"
    items:
      - name: "Bitwarden"
        logo: "https://vault.bitwarden.com/favicon.ico"
        subtitle: "Password manager"
        tag: "app"
        url: "https://vault.vijayakumar.xyz"
        target: "_blank" # optional html a tag target attribute

      - name: "Uptime kuma"
        logo: "https://flytime.fly.dev/favicon.ico"
        subtitle: "self-hosted monitoring tool"
        tag: "app"
        url: "https://flytime.fly.dev"
        slug: "vault" # Defaults to "default" if not provided.
        type: "UptimeKuma"
        target: "_blank"

      - name: "Immich"
        logo: "https://immich.app/img/favicon.png"
        subtitle: "Google photos alternative"
        tag: "service"
        url: "https://photos.vijayakumar.xyz/"
        target: "_blank"

      - name: "Jellyfin"
        logo: "https://jellyfin.org/images/favicon.ico"
        subtitle: "Self-hosted media streaming system"
        tag: "service"
        url: "https://jellyfin.vijayakumar.xyz/"
        target: "_blank"

      - name: "Umami"
        logo: "https://umami-vijay.vercel.app/favicon.ico"
        subtitle: "Umami is a privacy-focused alternative to Google Analytics."
        tag: "app"
        url: "https://umami-vijay.vercel.app/dashboard"
        target: "_blank"

      - name: "Onelink"
        logo: "http://0.gravatar.com/avatar/7fe9c540c91d52fb69830fb0d77036dc"
        subtitle: "Link in bio tool"
        tag: "app"
        url: "https://onelink-vijay.vercel.app"
        target: "_blank"

  - name: "Local"
    icon: "fas fa-server"
    items:      
      - name: "Dockge"
        logo: "https://dockge.kuma.pet/icon.svg"
        subtitle: "easy-to-use docker compose stack manager"
        tag: "app"
        url: "http://10.0.0.3:5001/"
        target: "_blank"
      
      - name: "Jellyseerr"
        logo: "https://github.com/Fallenbagel/jellyseerr/blob/develop/public/android-chrome-512x512.png?raw=true"
        subtitle: "Media requesting system"
        tag: "app"
        url: "http://10.0.0.3:5055/"
        target: "_blank"
      
      - name: "Pihole"
        logo: "https://docs.pi-hole.net/images/favicon.ico"
        subtitle: "Dns ad blocker"
        tag: "app"
        url: "http://10.0.0.2/admin"
        apikey: "3875b6b52bad0be6f8214321f867d149c05f6e9d55e35f303f350d55c12376f3"
        type: "PiHole"
        target: "_blank"

      - name: "Duplicati"
        logo: "https://www.duplicati.com/images/duplicati-fb-share-v1.png"
        subtitle: "Remote backup solution"
        tag: "app"
        url: "http://10.0.0.3:8200/"
        target: "_blank"

      - name: "QBittorrent"
        logo: "https://www.qbittorrent.org/favicon.svg"
        subtitle: "Torrent downloader"
        tag: "app"
        url: "http://10.0.0.3:8080/"
        target: "_blank"
      
  - name: "Media"
    icon: "fas fa-server"
    items:      
      - name: "Pihole"
        logo: "https://docs.pi-hole.net/images/favicon.ico"
        subtitle: "Dns ad blocker"
        tag: "app"
        url: "http://10.0.0.2/admin"
        apikey: "3875b6b52bad0be6f8214321f867d149c05f6e9d55e35f303f350d55c12376f3"
        type: "PiHole"
        target: "_blank"

      - name: "Duplicati"
        logo: "https://www.duplicati.com/images/duplicati-fb-share-v1.png"
        subtitle: "Remote backup solution"
        tag: "app"
        url: "http://10.0.0.3:8200/"
        target: "_blank"

      - name: "QBittorrent"
        logo: "https://www.qbittorrent.org/favicon.svg"
        subtitle: "Torrent downloader"
        tag: "app"
        url: "http://10.0.0.3:8080/"
        target: "_blank"
